services:
  # Next.js frontend
  web:
    build: ./web-next
    container_name: web-next-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=https://all-web-1.onrender.com
